[tools]
argon = "argon-rbx/argon@2.0.24"
stylua = "JohnnyMorganz/stylua@2.1.0"
selene = "Kampfkarren/selene@0.28.0"
wally = "UpliftGames/wally@0.3.2"
wally-package-types = "JohnnyMorganz/wally-package-types@1.5.1"
